# NumPy

In [5]:
import numpy as np

In [6]:
np.__version__

'1.26.4'

In [7]:
np.version.version

'1.26.4'

In [8]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [10]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [11]:
c=np.concatenate([a,b])
c

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [12]:
Aa=np.ones([3,3])
Bb=np.zeros([3,3])
cc=np.concatenate([Aa,Bb])
cc

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
Aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
Bb

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.concatenate([Aa,Bb])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
print(type(cc))

<class 'numpy.ndarray'>


In [17]:
cc.shape

(6, 3)

In [18]:
cc.size

18

In [19]:
abc=range(0,100,2)
for i in abc:
    print(i,end=',')

0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,

In [20]:
print(type(abc))

<class 'range'>


In [21]:
type(abc)

range

In [22]:
ac=range(0,100,5)
for i in ac:
    print(i,sep=',')

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95


In [23]:
a=np.arange(10,50,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [24]:
np.random.randint(1,100,5)

array([ 9, 35, 76, 73, 82])

In [25]:
r=np.arange(10,20,2)
print(r)

[10 12 14 16 18]


In [26]:
type(r)

numpy.ndarray

In [27]:
r[2]

14

In [28]:
r[2]=13
print(r)

[10 12 13 16 18]


In [29]:
r

array([10, 12, 13, 16, 18])

In [30]:
b=np.append(a,21)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 21])

In [31]:
c=np.append(a,[22,23])
c

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 22, 23])

In [32]:
d=np.delete(c,2)
c

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 22, 23])

In [33]:
e=np.delete(c,[1,2])
e

array([10, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46,
       48, 22, 23])

In [34]:
np.sort([23,42,55,75,42,12,57,6,58,33,18])

array([ 6, 12, 18, 23, 33, 42, 42, 55, 57, 58, 75])

In [35]:
a=np.array([1,15,25])
b=a.copy()
print(a)
print(b)

[ 1 15 25]
[ 1 15 25]


In [36]:
a=np.array([3.1426,2.755,1.958])
np.around(a,2)

array([3.14, 2.76, 1.96])

In [37]:
a.ndim

1

In [38]:
a.shape

(3,)

In [39]:
a.size

3